### ISSUE TITLE
Logging in with Google no longer works

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#333]
When attempting to log in, the user gets redirected to this page:

https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by adrianbanks** [comment]
This was fixed by the `fix-google-logins` branch, but the deployment failed due to an odd issue on Azure so it had to be pulled out. #337 is the re-do of the branch, but it can't be merged until the deployment issue is sorted.

**Comment by mikeparker** [comment]
Just FYI this is still an issue, I'm re-registering with my GitHub account instead. I hope this doesn't cause any problems!

**Comment by adrianbanks** [comment]
@mikeparker It looks like you were already registered with your GitHub login anyway.
